title: MOLGENIS
email: your-email@domain.com
description: MOLGENIS open source project website.
layout: black #default layout
url: http://www.molgenis.or

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-target-blank
exclude:
  - Gemfile
  - Gemfile.lock
